# Site settings
title: MovieMaven
description: Get the latest news, reviews, and ratings for all your favorite movies on MovieMaven.
baseurl: "/MovieMaven" # the subpath of your site, e.g. /blog/
url: "https://fatemeebrahimzadeh.github.io/" # the base hostname & protocol for your site

# Build settings
theme: your-theme
plugins:
  - your-plugin
